apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localvolumereplicasnapshotrecovers.hwameistor.io
spec:
  group: hwameistor.io
  names:
    kind: LocalVolumeReplicaSnapshotRecover
    listKind: LocalVolumeReplicaSnapshotRecoverList
    plural: localvolumereplicasnapshotrecovers
    shortNames:
    - lvrsrecover
    - lvrsnaprecover
    singular: localvolumereplicasnapshotrecover
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Node to recover
      jsonPath: .spec.nodeName
      name: nodeName
      type: string
    - description: Target for the recover
      jsonPath: .spec.targetVolume
      name: targetvolume
      type: string
    - description: Source snapshot for the recover
      jsonPath: .spec.sourceVolumeSnapshot
      name: sourcesnapshot
      type: string
    - description: State of the recover
      jsonPath: .status.state
      name: state
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: LocalVolumeReplicaSnapshotRecover is the Schema for the localvolumereplicasnapshotrecovers
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LocalVolumeReplicaSnapshotRecoverSpec defines the desired
              state of LocalVolumeReplicaSnapshotRecover
            properties:
              abort:
                default: false
                description: Abort can be used to abort the recover operation and
                  clean up sub resources created by the recover operation automatically
                type: boolean
              nodeName:
                description: NodeName is the name of the node that snapshot will be
                  recovered at
                type: string
              recoverType:
                default: restore
                description: RecoverType is the type about how to recover the volume,
                  e.g. rollback, restore. By default restore.
                enum:
                - rollback
                - restore
                type: string
              sourceVolumeReplicaSnapshot:
                description: SourceVolumeReplicaSnapshot represents which replica
                  snapshot is used for volume to recover from
                type: string
              sourceVolumeSnapshot:
                description: SourceVolumeSnapshot represents which snapshot is used
                  for volume to recover from
                type: string
              targetPoolName:
                description: TargetVolume is the name of the target volume will place
                  at
                type: string
              targetVolume:
                description: TargetVolume is the name of the volume to recover to
                type: string
              volumeSnapshotRecover:
                type: string
            required:
            - nodeName
            - recoverType
            - sourceVolumeReplicaSnapshot
            - sourceVolumeSnapshot
            - targetPoolName
            - targetVolume
            - volumeSnapshotRecover
            type: object
          status:
            description: LocalVolumeReplicaSnapshotRecoverStatus defines the observed
              state of LocalVolumeReplicaSnapshotRecover
            properties:
              message:
                description: Message error message to describe some states
                type: string
              state:
                description: State is the phase of recover volume snapshot, e.g. submitted,
                  started, completed, abort, ...
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
